import Link from "next/link";
import { ThemeToggle } from "@/components/theme-toggle";

export default function HomePage() {
  return (
    <main className="hero">
      <div className="floating-tools">
        <ThemeToggle />
      </div>
      <section className="hero-content">
        <img className="hero-logo" src="/homex-logo.png" alt="HOMEX" />
        <p className="eyebrow">Home recovery coordination</p>
        <h1>Bring your loved one home with everyone on the same page.</h1>
        <p>
          HOMEX keeps discharge instructions, family tasks, medication schedules, aide notes,
          documents, visits, and caregiver videos organized in one secure place.
        </p>
        <div className="actions">
          <Link className="button" href="/dashboard">View care dashboard</Link>
        </div>
        <p className="hero-note">
          Family members join through invite links generated by the circle owner.
        </p>
      </section>
    </main>
  );
}
